title: Doing the Don, Daily
theme: jekyll-theme-cayman
author: Don Krasky
email: dkrasky@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Don Krasky; Surfer, Snowboarder, and Applied Mathematics Ph.D.

# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  DonKrasky # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
